-- First, delete all existing records from the teachers table
DELETE FROM teachers;

-- Insert new records from the JSON file
INSERT INTO teachers (first_name, last_name, email, class, subject) VALUES
('Sarah', 'Johnson', 'sarah.johnson@school.edu', '9A', 'Mathematics'),
('Sarah', 'Chen', 'sarah.chen@school.edu', '10B', 'Physics'),
('Emily', 'Johnson', 'emily.johnson@school.edu', '11C', 'English Literature'),
('David', 'Kim', 'david.kim@school.edu', '12A', 'Mathematics'),
('Lisa', 'Patel', 'lisa.patel@school.edu', '9B', 'Biology'),
('James', 'Wilson', 'james.wilson@school.edu', '10A', 'Biology'),
('Maria', 'Garcia', 'maria.garcia@school.edu', '11B', 'Spanish'),
('Robert', 'Taylor', 'robert.taylor@school.edu', '12B', 'History'),
('Jennifer', 'Anderson', 'jennifer.anderson@school.edu', '9C', 'Art'),
('William', 'Brown', 'william.brown@school.edu', '10C', 'Physical Education'),
('Sophia', 'Martinez', 'sophia.martinez@school.edu', '11A', 'French'),
('Daniel', 'Lee', 'daniel.lee@school.edu', '12C', 'Economics'),
('Emma', 'Thompson', 'emma.thompson@school.edu', '9D', 'Music'),
('Christopher', 'White', 'christopher.white@school.edu', '10D', 'Geography'),
('Olivia', 'Harris', 'olivia.harris@school.edu', '11D', 'Psychology'),
('Matthew', 'Clark', 'matthew.clark@school.edu', '12D', 'Business Studies'),
('Isabella', 'Lewis', 'isabella.lewis@school.edu', '9E', 'Drama'),
('Andrew', 'Walker', 'andrew.walker@school.edu', '10E', 'Environmental Science'),
('Ava', 'Hall', 'ava.hall@school.edu', '11E', 'Sociology'),
('Joseph', 'Allen', 'joseph.allen@school.edu', '12E', 'Political Science'),
('Mia', 'Young', 'mia.young@school.edu', '9F', 'Dance'),
('Benjamin', 'King', 'benjamin.king@school.edu', '10F', 'Astronomy'),
('Charlotte', 'Wright', 'charlotte.wright@school.edu', '11F', 'Philosophy'),
('Samuel', 'Lopez', 'samuel.lopez@school.edu', '12F', 'Statistics'),
('Amelia', 'Hill', 'amelia.hill@school.edu', '9G', 'Photography'),
('Henry', 'Scott', 'henry.scott@school.edu', '10G', 'Robotics'),
('Harper', 'Green', 'harper.green@school.edu', '11G', 'Anthropology'),
('Sebastian', 'Adams', 'sebastian.adams@school.edu', '12G', 'Engineering'),
('Evelyn', 'Baker', 'evelyn.baker@school.edu', '9H', 'Design'),
('Jack', 'Gonzalez', 'jack.gonzalez@school.edu', '10H', 'Meteorology'),
('Abigail', 'Nelson', 'abigail.nelson@school.edu', '11H', 'Archaeology'),
('Owen', 'Carter', 'owen.carter@school.edu', '12H', 'Architecture'),
('Elizabeth', 'Mitchell', 'elizabeth.mitchell@school.edu', '9I', 'Ceramics'),
('Gabriel', 'Perez', 'gabriel.perez@school.edu', '10I', 'Oceanography'),
('Sofia', 'Roberts', 'sofia.roberts@school.edu', '11I', 'Linguistics'),
('Carter', 'Turner', 'carter.turner@school.edu', '12I', 'Biotechnology'),
('Avery', 'Phillips', 'avery.phillips@school.edu', '9J', 'Graphic Design'),
('Julian', 'Campbell', 'julian.campbell@school.edu', '10J', 'Geology'),
('Ella', 'Parker', 'ella.parker@school.edu', '11J', 'Criminology'),
('Wyatt', 'Evans', 'wyatt.evans@school.edu', '12J', 'Data Science'),
('Scarlett', 'Edwards', 'scarlett.edwards@school.edu', '9K', 'Digital Media'),
('Leo', 'Collins', 'leo.collins@school.edu', '10K', 'Paleontology'),
('Victoria', 'Stewart', 'victoria.stewart@school.edu', '11K', 'Ethics'),
('Hudson', 'Sanchez', 'hudson.sanchez@school.edu', '12K', 'Artificial Intelligence'),
('Madison', 'Morris', 'madison.morris@school.edu', '9L', 'Film Studies'),
('Lincoln', 'Rogers', 'lincoln.rogers@school.edu', '10L', 'Botany'),
('Luna', 'Reed', 'luna.reed@school.edu', '11L', 'Gender Studies'),
('Elias', 'Cook', 'elias.cook@school.edu', '12L', 'Cybersecurity'),
('Grace', 'Morgan', 'grace.morgan@school.edu', '9M', 'Animation'),
('Felix', 'Bell', 'felix.bell@school.edu', '10M', 'Zoology'),
('Chloe', 'Murphy', 'chloe.murphy@school.edu', '11M', 'Cultural Studies'),
('Adrian', 'Bailey', 'adrian.bailey@school.edu', '12M', 'Quantum Physics'),
('Penelope', 'Rivera', 'penelope.rivera@school.edu', '9N', 'Web Design'),
('Axel', 'Cooper', 'axel.cooper@school.edu', '10N', 'Marine Biology'),
('Layla', 'Richardson', 'layla.richardson@school.edu', '11N', 'Media Studies'),
('Atlas', 'Cox', 'atlas.cox@school.edu', '12N', 'Nanotechnology'),
('Nova', 'Howard', 'nova.howard@school.edu', '9O', 'Game Design'),
('Silas', 'Ward', 'silas.ward@school.edu', '10O', 'Ecology'),
('Aurora', 'Torres', 'aurora.torres@school.edu', '11O', 'Peace Studies'),
('Atticus', 'Peterson', 'atticus.peterson@school.edu', '12O', 'Blockchain Technology'),
('Iris', 'Gray', 'iris.gray@school.edu', '9P', 'UI/UX Design'),
('Jasper', 'Ramirez', 'jasper.ramirez@school.edu', '10P', 'Genetics'),
('Ruby', 'James', 'ruby.james@school.edu', '11P', 'Global Studies'),
('Miles', 'Watson', 'miles.watson@school.edu', '12P', 'Machine Learning'),
('Hazel', 'Brooks', 'hazel.brooks@school.edu', '9Q', '3D Modeling'),
('Theo', 'Kelly', 'theo.kelly@school.edu', '10Q', 'Virology'),
('Violet', 'Sanders', 'violet.sanders@school.edu', '11Q', 'Human Rights'),
('Finn', 'Price', 'finn.price@school.edu', '12Q', 'Cloud Computing'),
('Willow', 'Bennett', 'willow.bennett@school.edu', '9R', 'Digital Art'),
('Kai', 'Wood', 'kai.wood@school.edu', '10R', 'Immunology'),
('Rose', 'Barnes', 'rose.barnes@school.edu', '11R', 'International Relations'),
('Rowan', 'Ross', 'rowan.ross@school.edu', '12R', 'Virtual Reality'),
('Daisy', 'Henderson', 'daisy.henderson@school.edu', '9S', 'Motion Graphics'),
('Arlo', 'Coleman', 'arlo.coleman@school.edu', '10S', 'Neuroscience'),
('Poppy', 'Jenkins', 'poppy.jenkins@school.edu', '11S', 'Social Justice'),
('Rhys', 'Perry', 'rhys.perry@school.edu', '12S', 'Augmented Reality'),
('Lily', 'Powell', 'lily.powell@school.edu', '9T', 'Visual Effects'),
('Atlas', 'Long', 'atlas.long@school.edu', '10T', 'Biochemistry'),
('Ivy', 'Patterson', 'ivy.patterson@school.edu', '11T', 'Environmental Justice'),
('Felix', 'Hughes', 'felix.hughes@school.edu', '12T', 'Internet of Things'); 